version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: produtos_db
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: your_secure_password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data # Monta o volume para persistência de dados
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "myuser", "-d", "produtos_db"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      POSTGRES_DB: produtos_db
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: your_secure_password
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
    driver: local
